export const birthdayWishes = [
  "On your special day, may you feel surrounded by love, warmth, and the affection of those who cherish you. Happy birthday!",
  "Wishing you a birthday filled with the warmth of love and the joy of shared moments with your loved ones. Happy birthday!",
  "May this day be a reminder of how much you are loved and how warm your presence makes the world. Happy birthday!",
  "As you celebrate another year of life, know that you are a treasure, and your heart is a source of warmth and love. Happy birthday!",
  "Today, let the love and warmth of those who care about you fill your heart and make your birthday truly special. Happy birthday!",
  "Wishing you a day filled with the gentle embrace of love and the cozy warmth of cherished moments. Happy birthday!",
  "Your birthday is not just a day to get older but a day to be wrapped in the love and warmth of the people who care about you. Happy birthday!",
  "May the love in your heart be mirrored by the love surrounding you on this special day. Happy birthday!",
  "Here's to a day of celebrating not just your age but the depth of love and warmth in your life. Happy birthday!",
  "On your birthday, may the love that surrounds you be as bright as the candles on your cake. Happy birthday!",
  "As you blow out the candles, may you feel the warmth and love that only a birthday can bring. Happy birthday!",
  "Your presence in our lives brings so much love and warmth. Today, it's time to celebrate you. Happy birthday!",
  "Wishing you a birthday that's as warm and wonderful as the love you bring into the world. Happy birthday!",
  "May the love and warmth in your heart continue to shine and make the world a better place. Happy birthday!",
  "On your special day, may you feel the embrace of love and the cozy warmth of cherished moments. Happy birthday!",
  "As you celebrate another year of life, remember that you are surrounded by love and warmth. Happy birthday!",
  "Here's to a day of feeling loved, appreciated, and warmed by the affection of those who care about you. Happy birthday!",
  "May your birthday be a day when your heart is filled with love and your spirit is warmed by the presence of loved ones. Happy birthday!",
  "Wishing you a day that's as cozy and heartwarming as the love you bring into our lives. Happy birthday!",
  "May your birthday be a reminder of how loved and cherished you are by all those lucky enough to know you. Happy birthday!",
  "On this special day, may you be wrapped in the love and warmth of family and friends. Happy birthday!",
  "May your heart be filled with the love that surrounds you on your birthday. Happy birthday!",
  "As you celebrate another year, may you feel the love and warmth of the people who appreciate your presence in their lives. Happy birthday!",
  "Wishing you a day of love, laughter, and the warmth of cherished memories. Happy birthday!",
  "Your birthday is a day to reflect on the love and happiness you bring into the world. Happy birthday!",
  "Here's to a day of celebrating the beautiful soul that you are and the love you share with all of us. Happy birthday!",
  "May your birthday be a day of warmth, love, and the realization of how special you are to all of us. Happy birthday!",
  "On your special day, may you be surrounded by love, warmth, and the people who hold you dear. Happy birthday!",
  "Wishing you a birthday that's as heartwarming as the love you've shared with all of us. Happy birthday!",
  "May your heart be filled with the love and warmth of the people who care about you. Happy birthday!",
  "Here's to a day when your heart is as full as your smile, and your spirit is as warm as your presence. Happy birthday!",
  "As you celebrate another year, remember that the love in your heart is mirrored by the love that surrounds you. Happy birthday!",
  "May your birthday be a day of feeling cherished, loved, and appreciated by all of us. Happy birthday!",
  "Wishing you a day of joy, love, and the comforting warmth of shared moments. Happy birthday!",
  "Your birthday is a celebration of the love and warmth you bring into the lives of everyone you know. Happy birthday!",
  "May your special day be filled with the love of family and friends, making you feel truly blessed. Happy birthday!",
  "On your birthday, may you feel the warmth of love and the embrace of those who treasure you. Happy birthday!",
  "Wishing you a day that's as radiant as your heart and as heartwarming as your presence. Happy birthday!",
  "May your birthday be a day when the love in your heart is mirrored by the love surrounding you. Happy birthday!",
  "Here's to a day when you are wrapped in love, joy, and the affection of those who care about you. Happy birthday!",
  "As you blow out the candles, may the love and warmth in your life burn even brighter. Happy birthday!",
  "On your special day, may your heart be filled with love, your spirit with warmth, and your life with happiness. Happy birthday!",
  "Wishing you a birthday that's as cozy and heartwarming as the love you bring to others. Happy birthday!",
  "May your birthday be a day when you are reminded of how cherished and loved you are by all of us. Happy birthday!",
  "As you celebrate another year of life, know that you are a source of love and warmth to those who know you. Happy birthday!",
  "Here's to a day of feeling loved, appreciated, and surrounded by the affection of those who care about you. Happy birthday!",
  "May your heart be filled with the love that surrounds you on this special day. Happy birthday!",
];

// These 50 heartwarming birthday wishes will surely make the receiver feel loved and warm on their special day. 🎂🥰
